# Use the official Red Hat Universal Base Image for Node.js 18
FROM registry.access.redhat.com/ubi10/nodejs-24-minimal:latest

# Set the working directory inside the container
WORKDIR /opt/app-root/src

# Copy dependency manifests
COPY package*.json ./

# Install production dependencies
# Using 'npm ci' is recommended for automated environments for cleaner installs
RUN npm install --only=production

# Copy the rest of your application code
COPY . .

# Express app port
EXPOSE 3000

# Start the application
CMD [ "node", "app.js" ]
